import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Footer from "@/components/Footer";
import QueryProvider from "@/components/QueryProvider";
import { Toaster } from "@/components/ui/toaster";
import { auth } from "@/auth";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "@/components/theme-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "lynxlink",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <QueryProvider>
      <SessionProvider session={session}>
        <html lang="en" className="w-full">
          <body
            className={cn(
              "relative h-full font-sans antialiased",
              inter.className
            )}
            suppressHydrationWarning
          >
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <main className="relative flex flex-col min-h-screen">
                {/* <Navbar /> */}
                <div className="flex-grow flex-1">
                  {children} <Toaster />
                </div>
                <Footer />
              </main>
            </ThemeProvider>
          </body>
        </html>
      </SessionProvider>
    </QueryProvider>
  );
}
